language: java
jdk: oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: "ecomm-company"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ecomm-company_ecomm-log-monitor
